[tool.poetry]
name = "langchain-tutorials"
version = "0.1.0"
description = ""
authors = ["Rishil Ramesh <rishil.ramesh@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
langchain-openai = "^0.1.8"
langchain-core = "^0.2.7"
langchain-community = "^0.2.5"
python-dotenv = "^1.0.1"
streamlit = "^1.35.0"
tenacity = "8.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
